/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.JPanels;

import controller.NaveController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ce___
 */
public class CrearRackEnNave extends javax.swing.JPanel {
    private final NaveController naveCtrl;
    private List<String> naves;
    private int idNave;
    
    /**
     * Creates new form Principal
     */
    public CrearRackEnNave(NaveController naveCtrl) {
        this.naveCtrl = naveCtrl;
        initComponents();
        panelExito(false);
        //visibilidad elementos para la version comboBox
        botonSeleccionar.setVisible(false);
        navesComboBox.setVisible(false);
        noHayNaves.setVisible(false);
        // Evita que GroupLayout fuerce a centrar el panel
        navesPanel.setPreferredSize(new Dimension(navesPanel.getWidth(), 80));
        navesPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 80));
        panelExito.setPreferredSize(new Dimension(navesPanel.getWidth(), 220));
        panelExito.setMaximumSize(new Dimension(Integer.MAX_VALUE, 220));

        navesPanel.setLayout(new BoxLayout(navesPanel, BoxLayout.X_AXIS));
        navesPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        naves = naveCtrl.listarNaves();
        
        if (naves.isEmpty()){
            noHayNaves.setVisible(true);
        }
        if (naves.size() > 4){
            navesComboBox.removeAllItems();
            comboBoxNaves();
        } else {
            botonesNave();
        }
    }
    
    private void panelExito(boolean visible){
        exitoCrear.setVisible(visible);
        mensajeExito.setVisible(visible);
        idRackLabel.setVisible(visible);
    }
    
    private void comboBoxNaves(){
        botonSeleccionar.setVisible(true);
        navesComboBox.setVisible(true);
        for (String nave : naves) {
            navesComboBox.addItem(nave);
        }
    }
    
    private void botonesNave(){

        ImageIcon icono = new ImageIcon("Resources/img/nave.png");
        List<JLabel> labelsNave = new ArrayList<>();
        
        for (String nave : naves) {
            JLabel label = new JLabel(nave, icono, JLabel.LEFT);
            label.setFont(new Font("Roboto", Font.BOLD, 18));
            label.setForeground(Color.WHITE);
            label.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));
            label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            labelsNave.add(label);

            
            label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    idNave = Integer.parseInt(nave.split(" ")[2]); 
                    label.setOpaque(true);
                    for (JLabel lbl : labelsNave) {
                        lbl.setBackground(new Color(0,102,102)); // color original
                    }
                    label.setBackground(new Color(0,51,51)); // seleccionado
                }
            });
            label.setBackground(new Color(0,102,102));
            navesPanel.add(label);
        }
        navesPanel.revalidate();
        navesPanel.repaint();
    }
    
    private void crearRack() {
        int idRack = naveCtrl.crearRack(idNave);
        
        if (idRack == 0){
            JOptionPane.showMessageDialog(this, "Error creando el rack", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        idRackLabel.setText("Rack con ID "+idRack);
        panelExito(true);
        
    } 

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        navesPanel = new javax.swing.JPanel();
        navesComboBox = new javax.swing.JComboBox<>();
        botonSeleccionar = new javax.swing.JButton();
        noHayNaves = new javax.swing.JLabel();
        ingrese = new javax.swing.JLabel();
        panelExito = new javax.swing.JPanel();
        crearRack = new javax.swing.JButton();
        exitoCrear = new javax.swing.JPanel();
        mensajeExito = new javax.swing.JLabel();
        idRackLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 232, 232));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(580, 400));

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Menú naves  >  Crear rack");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navesPanel.setBackground(new java.awt.Color(0, 102, 102));

        navesComboBox.setBackground(new java.awt.Color(255, 255, 255));
        navesComboBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        navesComboBox.setForeground(new java.awt.Color(51, 51, 51));
        navesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        navesComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        botonSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        botonSeleccionar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonSeleccionar.setForeground(new java.awt.Color(0, 51, 51));
        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botonSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        noHayNaves.setBackground(new java.awt.Color(255, 255, 255));
        noHayNaves.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        noHayNaves.setForeground(new java.awt.Color(255, 255, 255));
        noHayNaves.setText("No hay naves registradas");

        javax.swing.GroupLayout navesPanelLayout = new javax.swing.GroupLayout(navesPanel);
        navesPanel.setLayout(navesPanelLayout);
        navesPanelLayout.setHorizontalGroup(
            navesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navesPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(navesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(noHayNaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navesPanelLayout.setVerticalGroup(
            navesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(navesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noHayNaves))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        ingrese.setBackground(new java.awt.Color(255, 255, 255));
        ingrese.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ingrese.setForeground(new java.awt.Color(0, 51, 51));
        ingrese.setText("Seleccione una nave:");

        panelExito.setBackground(new java.awt.Color(255, 255, 255));

        crearRack.setBackground(new java.awt.Color(0, 51, 51));
        crearRack.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        crearRack.setForeground(new java.awt.Color(255, 255, 255));
        crearRack.setText("CREAR RACK");
        crearRack.setBorder(null);
        crearRack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRackActionPerformed(evt);
            }
        });

        exitoCrear.setBackground(new java.awt.Color(238, 238, 238));

        mensajeExito.setBackground(new java.awt.Color(181, 255, 181));
        mensajeExito.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        mensajeExito.setForeground(new java.awt.Color(0, 0, 0));
        mensajeExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeExito.setText("¡Rack creado con éxito!");
        mensajeExito.setOpaque(true);

        idRackLabel.setBackground(new java.awt.Color(255, 255, 255));
        idRackLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        idRackLabel.setForeground(new java.awt.Color(0, 51, 51));
        idRackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idRackLabel.setText("ID Rack");

        javax.swing.GroupLayout exitoCrearLayout = new javax.swing.GroupLayout(exitoCrear);
        exitoCrear.setLayout(exitoCrearLayout);
        exitoCrearLayout.setHorizontalGroup(
            exitoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitoCrearLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(exitoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensajeExito, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(idRackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        exitoCrearLayout.setVerticalGroup(
            exitoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitoCrearLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(mensajeExito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idRackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelExitoLayout = new javax.swing.GroupLayout(panelExito);
        panelExito.setLayout(panelExitoLayout);
        panelExitoLayout.setHorizontalGroup(
            panelExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExitoLayout.createSequentialGroup()
                .addGroup(panelExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExitoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(exitoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelExitoLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(crearRack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelExitoLayout.setVerticalGroup(
            panelExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExitoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(crearRack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(exitoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ingrese)
                .addContainerGap(435, Short.MAX_VALUE))
            .addComponent(panelExito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingrese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelExito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        String nave = (String) navesComboBox.getSelectedItem();
        idNave = Integer.parseInt(nave.split(" ")[2]);
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void crearRackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRackActionPerformed
        crearRack();
    }//GEN-LAST:event_crearRackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JButton crearRack;
    private javax.swing.JPanel exitoCrear;
    private javax.swing.JButton filtrar;
    private javax.swing.JButton filtrar1;
    private javax.swing.JLabel idRackLabel;
    private javax.swing.JLabel ingrese;
    private javax.swing.JLabel mensajeExito;
    private javax.swing.JComboBox<String> navesComboBox;
    private javax.swing.JPanel navesPanel;
    private javax.swing.JLabel noHayNaves;
    private javax.swing.JPanel panelExito;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
