/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.JPanels;

import controller.ProductoController;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.Producto;
import view.PrincipalJFrame;

/**
 *
 * @author Ce___
 */
public class ListadoProductos extends javax.swing.JPanel {
    private ProductoController productoCtrl;
    private PrincipalJFrame frame;
    private DefaultTableModel mt = new DefaultTableModel();
    /**
     * Creates new form Listado
     */
    public ListadoProductos(PrincipalJFrame frame, ProductoController productoCtrl) {
        initComponents();
        this.productoCtrl = productoCtrl;
        this.frame = frame;
        String[] ids = {"Código", "Descripción", "U medida", "Peso", "Capacidad envase", "Grupo"};
        mt.setColumnIdentifiers(ids);
        tablaProductos.setModel(mt);
        
        aplicarEstiloTabla();
        mostrarProductos();

    }
    
    private void aplicarEstiloTabla() {
        tablaProductos.setFont(new java.awt.Font("Roboto", 0, 14));
        tablaProductos.setRowHeight(28);

        // Quitar líneas horizontales/verticales
        tablaProductos.setShowHorizontalLines(false);
        tablaProductos.setShowVerticalLines(false);

        // Color de fondo
        tablaProductos.setBackground(new java.awt.Color(250, 250, 250)); // blanco suave
        tablaProductos.setForeground(new java.awt.Color(102,102,102));

        // Selección minimalista
        tablaProductos.setSelectionBackground(new java.awt.Color(220, 240, 240));
        tablaProductos.setSelectionForeground(new java.awt.Color(0, 50, 50));

        // Bordes suaves
        tablaProductos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaProductos.setGridColor(new java.awt.Color(240, 240, 240));

        // Header (encabezado)
        JTableHeader header = tablaProductos.getTableHeader();
        header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 30));
        header.setFont(new java.awt.Font("Roboto Light",Font.BOLD, 15));
        header.setOpaque(false);
        header.setBackground(Color.white);
        header.setForeground(new java.awt.Color(50, 50, 50));
        header.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        catLabel = new javax.swing.JLabel();
        filtrar = new javax.swing.JButton();
        categoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(670, 500));

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Menú productos  >  Listar productos");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        catLabel.setBackground(new java.awt.Color(255, 255, 255));
        catLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        catLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        catLabel.setText("Grupo");

        filtrar.setBackground(new java.awt.Color(0, 51, 51));
        filtrar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        filtrar.setForeground(new java.awt.Color(255, 255, 255));
        filtrar.setText("FILTRAR");
        filtrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        categoria.setBackground(new java.awt.Color(255, 255, 255));
        categoria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Materia prima", "Producto final", "Producto reenvasado", " " }));
        categoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tablaProductos.setBackground(new java.awt.Color(255, 255, 255));
        tablaProductos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaProductos.setForeground(new java.awt.Color(102, 102, 102));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Unidad de medida", "Peso unitario", "Capacidad contenedor", "Grupo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaProductos.setToolTipText("");
        tablaProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(catLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(catLabel)
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
       String cat = (String) categoria.getSelectedItem();
       mt.setRowCount(0);
       filtrarProductos(cat);
    }//GEN-LAST:event_filtrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catLabel;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JButton filtrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel subTitle;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
    
    private void mostrarProductos(){
        List<Producto> productos = productoCtrl.listarProductosObjeto();
        for (Producto p : productos){
            agregarFila(p);
        }
    }
    
    private void filtrarProductos(String grupo){
        if (grupo.equals("Todas")){
            mt.setRowCount(0);
            mostrarProductos();
        }

        List<Producto> productos = productoCtrl.filtrarProductosGrupo(grupo);
        for (Producto p : productos){
            agregarFila(p);
        }
    }
    
    private void agregarFila(Producto p){
        mt.addRow(new Object[] {p.getCodigo() , p.getDescripcion(), p.getUnidadMedida(), p.getPesoUnitario(),
                p.getCapacidad(), p.getGrupo()});
    }
}
