/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.JPanels;

import controller.NaveController;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import view.PrincipalJFrame;

/**
 *
 * @author Ce___
 */
public class Naves extends javax.swing.JPanel {
    private NaveController naveCtrl;
    private PrincipalJFrame frame;
    private JPanel content;

    private Image backgroundImage;
    /**
     * Creates new form Productos
     */
    public Naves(PrincipalJFrame frame, NaveController naveCtrl) {
        this.frame = frame;
        this.naveCtrl = naveCtrl;
        content = new JPanel(new BorderLayout());
        backgroundImage = new ImageIcon(getClass().getResource("/img/bgIMG.png")).getImage();
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Dibujar la imagen de fondo escalada al tamaño del panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        subtituloNaves = new javax.swing.JLabel();
        crearNave = new javax.swing.JPanel();
        labelCrearNave = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        listarRacks = new javax.swing.JPanel();
        labelListarRacks = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        subtituloRacks = new javax.swing.JLabel();
        crearRack = new javax.swing.JPanel();
        arrow4 = new javax.swing.JLabel();
        labelCrearRack = new javax.swing.JLabel();
        pesoUbicacion = new javax.swing.JPanel();
        labelPesoUbicacionesRack = new javax.swing.JLabel();
        arrow6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 232, 232));
        setPreferredSize(new java.awt.Dimension(670, 500));

        container.setBackground(new java.awt.Color(255, 255, 255));

        subtituloNaves.setBackground(new java.awt.Color(255, 255, 255));
        subtituloNaves.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        subtituloNaves.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        subtituloNaves.setText("NAVES");

        crearNave.setBackground(new java.awt.Color(212, 235, 235));
        crearNave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearNaveMouseClicked(evt);
            }
        });

        labelCrearNave.setBackground(new java.awt.Color(212, 235, 235));
        labelCrearNave.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCrearNave.setForeground(new java.awt.Color(0, 51, 51));
        labelCrearNave.setText("  Crear nave");
        labelCrearNave.setOpaque(true);

        arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout crearNaveLayout = new javax.swing.GroupLayout(crearNave);
        crearNave.setLayout(crearNaveLayout);
        crearNaveLayout.setHorizontalGroup(
            crearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearNaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCrearNave, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow)
                .addContainerGap())
        );
        crearNaveLayout.setVerticalGroup(
            crearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearNaveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCrearNave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearNaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        listarRacks.setBackground(new java.awt.Color(212, 235, 235));
        listarRacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarRacksMouseClicked(evt);
            }
        });

        labelListarRacks.setBackground(new java.awt.Color(212, 235, 235));
        labelListarRacks.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelListarRacks.setForeground(new java.awt.Color(0, 51, 51));
        labelListarRacks.setText("  Listar racks de una nave");
        labelListarRacks.setOpaque(true);

        arrow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout listarRacksLayout = new javax.swing.GroupLayout(listarRacks);
        listarRacks.setLayout(listarRacksLayout);
        listarRacksLayout.setHorizontalGroup(
            listarRacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarRacksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelListarRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow1)
                .addContainerGap())
        );
        listarRacksLayout.setVerticalGroup(
            listarRacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarRacksLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarRacksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelListarRacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        subtituloRacks.setBackground(new java.awt.Color(255, 255, 255));
        subtituloRacks.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        subtituloRacks.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        subtituloRacks.setText("RACKS");

        crearRack.setBackground(new java.awt.Color(212, 235, 235));
        crearRack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearRackMouseClicked(evt);
            }
        });

        arrow4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        labelCrearRack.setBackground(new java.awt.Color(212, 235, 235));
        labelCrearRack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCrearRack.setForeground(new java.awt.Color(0, 51, 51));
        labelCrearRack.setText("  Crear rack en una nave");
        labelCrearRack.setOpaque(true);

        javax.swing.GroupLayout crearRackLayout = new javax.swing.GroupLayout(crearRack);
        crearRack.setLayout(crearRackLayout);
        crearRackLayout.setHorizontalGroup(
            crearRackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearRackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCrearRack, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow4)
                .addContainerGap())
        );
        crearRackLayout.setVerticalGroup(
            crearRackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearRackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearRackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCrearRack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pesoUbicacion.setBackground(new java.awt.Color(212, 235, 235));
        pesoUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesoUbicacionMouseClicked(evt);
            }
        });

        labelPesoUbicacionesRack.setBackground(new java.awt.Color(212, 235, 235));
        labelPesoUbicacionesRack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelPesoUbicacionesRack.setForeground(new java.awt.Color(0, 51, 51));
        labelPesoUbicacionesRack.setText("  Peso de ubicaciones disponibles");
        labelPesoUbicacionesRack.setOpaque(true);

        arrow6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout pesoUbicacionLayout = new javax.swing.GroupLayout(pesoUbicacion);
        pesoUbicacion.setLayout(pesoUbicacionLayout);
        pesoUbicacionLayout.setHorizontalGroup(
            pesoUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesoUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPesoUbicacionesRack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(arrow6)
                .addContainerGap())
        );
        pesoUbicacionLayout.setVerticalGroup(
            pesoUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesoUbicacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesoUbicacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPesoUbicacionesRack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtituloRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtituloNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarRacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearRack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesoUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(subtituloNaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listarRacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(subtituloRacks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearRack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pesoUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearNaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearNaveMouseClicked
       int id = naveCtrl.crearNave();
       JOptionPane.showMessageDialog(this, "Nave creada. ID " + id, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_crearNaveMouseClicked

    private void listarRacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarRacksMouseClicked
        frame.mostrarJPanel(new ListarNavesYRacks(naveCtrl));
    }//GEN-LAST:event_listarRacksMouseClicked

    private void crearRackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearRackMouseClicked
        frame.mostrarJPanel(new CrearRackEnNave(naveCtrl));
    }//GEN-LAST:event_crearRackMouseClicked

    private void pesoUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesoUbicacionMouseClicked
        frame.mostrarJPanel(new PesoUbicacionesRack(naveCtrl));
    }//GEN-LAST:event_pesoUbicacionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow;
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow4;
    private javax.swing.JLabel arrow6;
    private javax.swing.JPanel container;
    private javax.swing.JPanel crearNave;
    private javax.swing.JPanel crearRack;
    private javax.swing.JLabel labelCrearNave;
    private javax.swing.JLabel labelCrearRack;
    private javax.swing.JLabel labelListarRacks;
    private javax.swing.JLabel labelPesoUbicacionesRack;
    private javax.swing.JPanel listarRacks;
    private javax.swing.JPanel pesoUbicacion;
    private javax.swing.JLabel subtituloNaves;
    private javax.swing.JLabel subtituloRacks;
    // End of variables declaration//GEN-END:variables
}
