/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.JPanels;

import controller.ProductoController;
import java.awt.Color;
import javax.swing.JOptionPane;
import view.PrincipalJFrame;

/**
 *
 * @author Ce___
 */
public class NuevoProducto extends javax.swing.JPanel {
    private PrincipalJFrame frame;
    private ProductoController productoCtrl;

    /**
     * Creates new form NuevoProducto
     */
    public NuevoProducto(PrincipalJFrame frame, ProductoController productoCtrl) {
        initComponents();
        this.productoCtrl = productoCtrl;
        this.frame = frame;
    }
    
    private void registrarProducto(){
        try {
            String descripcion = jTextDescripcion.getText().trim();
            String unidadMedida = (String) jComboBoxUMed.getSelectedItem();
            double peso = Double.parseDouble(jFTextFieldPeso.getText().replace(",", "."));
            double capacidad = Double.parseDouble(jFTextFieldCapacidad.getText().replace(",", "."));
            int stockMin = Integer.parseInt(jFTextFieldStockMin.getText().trim());
            String grupo = (String) jComboBoxGrupo.getSelectedItem();
            System.out.println(descripcion + unidadMedida + peso + capacidad + stockMin + grupo);

            String respuesta = productoCtrl.agregarProducto(descripcion, unidadMedida, peso, capacidad, stockMin, grupo);

            if (respuesta == null || respuesta.isEmpty()) {
                System.out.println("res: " +respuesta);
                JOptionPane.showMessageDialog(this, "Error al crear el producto.\n" + respuesta, "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println(respuesta);
                JOptionPane.showMessageDialog(this, "Producto registrado correctamente:\n" + respuesta, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para peso y capacidad.", "Error de formato", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiarCampos() {
        jTextDescripcion.setText("");
        jFTextFieldPeso.setText("");
        jFTextFieldStockMin.setText("");
        jFTextFieldCapacidad.setText("");
        jComboBoxUMed.setSelectedIndex(0);
        jComboBoxGrupo.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        labelUnidad = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        labelPeso = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jFTextFieldPeso = new javax.swing.JFormattedTextField();
        labelStockMin = new javax.swing.JLabel();
        jFTextFieldStockMin = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        labelContenedor = new javax.swing.JLabel();
        labelCapacidad = new javax.swing.JLabel();
        jFTextFieldCapacidad = new javax.swing.JFormattedTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelUMedida = new javax.swing.JLabel();
        jComboBoxUMed = new javax.swing.JComboBox<>();
        labelGrupo = new javax.swing.JLabel();
        jComboBoxGrupo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JPanel();
        btnRegistrarTxt = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        btnLimpiarTxt = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(232, 232, 232));

        container.setBackground(new java.awt.Color(255, 255, 255));

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Menú productos  >  Registrar nuevo producto");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelUnidad.setBackground(new java.awt.Color(255, 255, 255));
        labelUnidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelUnidad.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        labelUnidad.setText("Unidad");

        labelDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(0, 51, 51));
        labelDescripcion.setText("DESCRIPCIÓN");

        jTextDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextDescripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextDescripcion.setBorder(null);
        jTextDescripcion.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextDescripcionMousePressed(evt);
            }
        });
        jTextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        labelPeso.setBackground(new java.awt.Color(255, 255, 255));
        labelPeso.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelPeso.setForeground(new java.awt.Color(0, 51, 51));
        labelPeso.setText("PESO (kg)");

        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));

        jFTextFieldPeso.setBackground(new java.awt.Color(255, 255, 255));
        jFTextFieldPeso.setBorder(null);
        jFTextFieldPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFTextFieldPeso.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFTextFieldPeso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jFTextFieldPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFTextFieldPesoMousePressed(evt);
            }
        });
        jFTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextFieldPesoActionPerformed(evt);
            }
        });

        labelStockMin.setBackground(new java.awt.Color(255, 255, 255));
        labelStockMin.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelStockMin.setForeground(new java.awt.Color(0, 51, 51));
        labelStockMin.setText("STOCK MÍNIMO");

        jFTextFieldStockMin.setBackground(new java.awt.Color(255, 255, 255));
        jFTextFieldStockMin.setBorder(null);
        jFTextFieldStockMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFTextFieldStockMin.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFTextFieldStockMin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jFTextFieldStockMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFTextFieldStockMinMousePressed(evt);
            }
        });
        jFTextFieldStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextFieldStockMinActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 51, 51));

        labelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        labelContenedor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelContenedor.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        labelContenedor.setText("Contenedor");

        labelCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        labelCapacidad.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelCapacidad.setForeground(new java.awt.Color(0, 51, 51));
        labelCapacidad.setText("CAPACIDAD (kg)");

        jFTextFieldCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        jFTextFieldCapacidad.setBorder(null);
        jFTextFieldCapacidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFTextFieldCapacidad.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFTextFieldCapacidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jFTextFieldCapacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFTextFieldCapacidadMousePressed(evt);
            }
        });
        jFTextFieldCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextFieldCapacidadActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 51, 51));

        labelUMedida.setBackground(new java.awt.Color(255, 255, 255));
        labelUMedida.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelUMedida.setForeground(new java.awt.Color(0, 51, 51));
        labelUMedida.setText("UNIDAD DE MEDIDA");

        jComboBoxUMed.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxUMed.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBoxUMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LITROS", "KILOS", "UNIDAD", "GRAMOS", "MILILITROS" }));
        jComboBoxUMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jComboBoxUMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUMedActionPerformed(evt);
            }
        });

        labelGrupo.setBackground(new java.awt.Color(255, 255, 255));
        labelGrupo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelGrupo.setForeground(new java.awt.Color(0, 51, 51));
        labelGrupo.setText("GRUPO");

        jComboBoxGrupo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxGrupo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia prima", "Producto final", "Producto reenvasado", " " }));
        jComboBoxGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 51));

        btnRegistrarTxt.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        btnRegistrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarTxt.setText("REGISTRAR");
        btnRegistrarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));

        btnLimpiarTxt.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        btnLimpiarTxt.setForeground(new java.awt.Color(0, 51, 51));
        btnLimpiarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarTxt.setText("LIMPIAR");
        btnLimpiarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDescripcion)
                            .addComponent(jTextDescripcion)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPeso)
                            .addComponent(jSeparator2)
                            .addComponent(jFTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelStockMin)
                            .addComponent(jFTextFieldStockMin)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(containerLayout.createSequentialGroup()
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(containerLayout.createSequentialGroup()
                            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelUMedida)
                                .addComponent(jComboBoxUMed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelGrupo)
                                .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(labelUnidad)
                .addGap(13, 13, 13)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescripcion)
                            .addComponent(labelPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFTextFieldStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(labelStockMin)
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelContenedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(labelGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGrupo))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCapacidad)
                            .addComponent(labelUMedida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUMed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addContainerGap(45, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addContainerGap(50, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextDescripcionMousePressed

    }//GEN-LAST:event_jTextDescripcionMousePressed

    private void jTextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescripcionActionPerformed

    private void jFTextFieldPesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextFieldPesoMousePressed

    }//GEN-LAST:event_jFTextFieldPesoMousePressed

    private void jFTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextFieldPesoActionPerformed

    private void jFTextFieldStockMinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextFieldStockMinMousePressed

    }//GEN-LAST:event_jFTextFieldStockMinMousePressed

    private void jFTextFieldStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextFieldStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextFieldStockMinActionPerformed

    private void jFTextFieldCapacidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextFieldCapacidadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextFieldCapacidadMousePressed

    private void jFTextFieldCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextFieldCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextFieldCapacidadActionPerformed

    private void jComboBoxUMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUMedActionPerformed

    private void btnRegistrarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTxtMouseClicked
        registrarProducto();
    }//GEN-LAST:event_btnRegistrarTxtMouseClicked

    private void btnRegistrarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTxtMouseEntered
        btnRegistrar.setBackground(new Color(0,87,87));
    }//GEN-LAST:event_btnRegistrarTxtMouseEntered

    private void btnRegistrarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTxtMouseExited
        btnRegistrar.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnRegistrarTxtMouseExited

    private void btnLimpiarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTxtMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarTxtMouseClicked

    private void btnLimpiarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTxtMouseEntered
        btnLimpiar.setBackground(new Color(224,224,224));
    }//GEN-LAST:event_btnLimpiarTxtMouseEntered

    private void btnLimpiarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTxtMouseExited
        btnLimpiar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnLimpiarTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JLabel btnLimpiarTxt;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JLabel btnRegistrarTxt;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JComboBox<String> jComboBoxGrupo;
    private javax.swing.JComboBox<String> jComboBoxUMed;
    private javax.swing.JFormattedTextField jFTextFieldCapacidad;
    private javax.swing.JFormattedTextField jFTextFieldPeso;
    private javax.swing.JFormattedTextField jFTextFieldStockMin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelContenedor;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelStockMin;
    private javax.swing.JLabel labelUMedida;
    private javax.swing.JLabel labelUnidad;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
