/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.JPanels;

import controller.ProductoController;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import view.PrincipalJFrame;

/**
 *
 * @author Ce___
 */
public class Productos extends javax.swing.JPanel {
    private ProductoController productoCtrl;
    private PrincipalJFrame frame;
    private JPanel content;

    private Image backgroundImage;
    /**
     * Creates new form Productos
     */
    public Productos(PrincipalJFrame frame, ProductoController productoCtrl) {
        this.frame = frame;
        this.productoCtrl = productoCtrl;
        content = new JPanel(new BorderLayout());
        backgroundImage = new ImageIcon(getClass().getResource("/img/bgIMG.png")).getImage();
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Dibujar la imagen de fondo escalada al tamaño del panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        registrarProducto = new javax.swing.JPanel();
        labelRegistrarProducto = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        verCatalogo = new javax.swing.JPanel();
        labelCatalogo = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        buscarProducto = new javax.swing.JPanel();
        labelBuscarProducto = new javax.swing.JLabel();
        arrow4 = new javax.swing.JLabel();
        eliminarProducto = new javax.swing.JPanel();
        labelEliminarProducto = new javax.swing.JLabel();
        arrow6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 232, 232));
        setPreferredSize(new java.awt.Dimension(670, 500));

        container.setBackground(new java.awt.Color(255, 255, 255));

        registrarProducto.setBackground(new java.awt.Color(212, 235, 235));
        registrarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarProductoMouseClicked(evt);
            }
        });

        labelRegistrarProducto.setBackground(new java.awt.Color(212, 235, 235));
        labelRegistrarProducto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelRegistrarProducto.setForeground(new java.awt.Color(0, 51, 51));
        labelRegistrarProducto.setText(" Registrar producto");
        labelRegistrarProducto.setOpaque(true);

        arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout registrarProductoLayout = new javax.swing.GroupLayout(registrarProducto);
        registrarProducto.setLayout(registrarProductoLayout);
        registrarProductoLayout.setHorizontalGroup(
            registrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow)
                .addContainerGap())
        );
        registrarProductoLayout.setVerticalGroup(
            registrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        verCatalogo.setBackground(new java.awt.Color(212, 235, 235));
        verCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verCatalogoMouseClicked(evt);
            }
        });

        labelCatalogo.setBackground(new java.awt.Color(212, 235, 235));
        labelCatalogo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCatalogo.setForeground(new java.awt.Color(0, 51, 51));
        labelCatalogo.setText(" Ver listado de productos");
        labelCatalogo.setOpaque(true);

        arrow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout verCatalogoLayout = new javax.swing.GroupLayout(verCatalogo);
        verCatalogo.setLayout(verCatalogoLayout);
        verCatalogoLayout.setHorizontalGroup(
            verCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow1)
                .addContainerGap())
        );
        verCatalogoLayout.setVerticalGroup(
            verCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verCatalogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        buscarProducto.setBackground(new java.awt.Color(212, 235, 235));
        buscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarProductoMouseClicked(evt);
            }
        });

        labelBuscarProducto.setBackground(new java.awt.Color(212, 235, 235));
        labelBuscarProducto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelBuscarProducto.setForeground(new java.awt.Color(0, 51, 51));
        labelBuscarProducto.setText(" Buscar producto");
        labelBuscarProducto.setOpaque(true);

        arrow4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout buscarProductoLayout = new javax.swing.GroupLayout(buscarProducto);
        buscarProducto.setLayout(buscarProductoLayout);
        buscarProductoLayout.setHorizontalGroup(
            buscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow4)
                .addContainerGap())
        );
        buscarProductoLayout.setVerticalGroup(
            buscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        eliminarProducto.setBackground(new java.awt.Color(212, 235, 235));
        eliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarProductoMouseClicked(evt);
            }
        });

        labelEliminarProducto.setBackground(new java.awt.Color(212, 235, 235));
        labelEliminarProducto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelEliminarProducto.setForeground(new java.awt.Color(0, 51, 51));
        labelEliminarProducto.setText(" Eliminar producto");
        labelEliminarProducto.setOpaque(true);

        arrow6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout eliminarProductoLayout = new javax.swing.GroupLayout(eliminarProducto);
        eliminarProducto.setLayout(eliminarProductoLayout);
        eliminarProductoLayout.setHorizontalGroup(
            eliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(arrow6)
                .addContainerGap())
        );
        eliminarProductoLayout.setVerticalGroup(
            eliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(registrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProductoMouseClicked
        frame.mostrarJPanel(new NuevoProducto(frame, productoCtrl));
    }//GEN-LAST:event_registrarProductoMouseClicked

    private void verCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCatalogoMouseClicked
        frame.mostrarJPanel(new ListadoProductos(frame, productoCtrl));
    }//GEN-LAST:event_verCatalogoMouseClicked

    private void buscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarProductoMouseClicked
        frame.mostrarJPanel(new BuscarProducto(frame, productoCtrl));
    }//GEN-LAST:event_buscarProductoMouseClicked

    private void eliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarProductoMouseClicked
        frame.mostrarJPanel(new EliminarProducto(frame, productoCtrl));
    }//GEN-LAST:event_eliminarProductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow;
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow4;
    private javax.swing.JLabel arrow6;
    private javax.swing.JPanel buscarProducto;
    private javax.swing.JPanel container;
    private javax.swing.JPanel eliminarProducto;
    private javax.swing.JLabel labelBuscarProducto;
    private javax.swing.JLabel labelCatalogo;
    private javax.swing.JLabel labelEliminarProducto;
    private javax.swing.JLabel labelRegistrarProducto;
    private javax.swing.JPanel registrarProducto;
    private javax.swing.JPanel verCatalogo;
    // End of variables declaration//GEN-END:variables
}
