/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProductoController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ce___
 */
public class NuevoProductoJFrame extends javax.swing.JFrame {
    private int xMouse, yMouse;
    private ProductoController productoCtrl;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoProductoJFrame.class.getName());

    /**
     * Creates new form NuevoProductoJFrame
     */
    public NuevoProductoJFrame(ProductoController productoCtrl) {
        initComponents();
        this.productoCtrl = productoCtrl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        btnPrincipal = new javax.swing.JButton();
        btnNaves = new javax.swing.JButton();
        btnMovimientos = new javax.swing.JButton();
        btnTransformacion = new javax.swing.JButton();
        btnTrazabilidad = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        btnExitX = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        labelPeso = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jFTextFieldPeso = new javax.swing.JFormattedTextField();
        labelStockMin = new javax.swing.JLabel();
        jFTextFieldStockMin = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        labelUMedida = new javax.swing.JLabel();
        jComboBoxUMed = new javax.swing.JComboBox<>();
        labelGrupo = new javax.swing.JLabel();
        jComboBoxGrupo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JPanel();
        btnRegistrarTxt = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        btnLimpiarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(232, 232, 232));
        bg.setMinimumSize(new java.awt.Dimension(900, 600));
        bg.setPreferredSize(new java.awt.Dimension(900, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(0, 51, 51));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("WMS");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/icon.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(512, 512));
        logo.setMinimumSize(new java.awt.Dimension(512, 512));
        logo.setPreferredSize(new java.awt.Dimension(512, 512));

        btnPrincipal.setBackground(new java.awt.Color(0, 51, 51));
        btnPrincipal.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/home.png"))); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.setToolTipText("");
        btnPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal.setBorderPainted(false);
        btnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal.setIconTextGap(12);
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        btnNaves.setBackground(new java.awt.Color(0, 51, 51));
        btnNaves.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnNaves.setForeground(new java.awt.Color(255, 255, 255));
        btnNaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/nave.png"))); // NOI18N
        btnNaves.setText("Naves");
        btnNaves.setToolTipText("");
        btnNaves.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnNaves.setBorderPainted(false);
        btnNaves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNaves.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNaves.setIconTextGap(12);
        btnNaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavesActionPerformed(evt);
            }
        });

        btnMovimientos.setBackground(new java.awt.Color(0, 51, 51));
        btnMovimientos.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/movimientos.png"))); // NOI18N
        btnMovimientos.setText("Movimientos");
        btnMovimientos.setToolTipText("");
        btnMovimientos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMovimientos.setBorderPainted(false);
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMovimientos.setIconTextGap(12);
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });

        btnTransformacion.setBackground(new java.awt.Color(0, 51, 51));
        btnTransformacion.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnTransformacion.setForeground(new java.awt.Color(255, 255, 255));
        btnTransformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/transformacion.png"))); // NOI18N
        btnTransformacion.setText("Transformación");
        btnTransformacion.setToolTipText("");
        btnTransformacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnTransformacion.setBorderPainted(false);
        btnTransformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransformacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransformacion.setIconTextGap(12);

        btnTrazabilidad.setBackground(new java.awt.Color(0, 51, 51));
        btnTrazabilidad.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnTrazabilidad.setForeground(new java.awt.Color(255, 255, 255));
        btnTrazabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/historial.png"))); // NOI18N
        btnTrazabilidad.setText("Trazabilidad");
        btnTrazabilidad.setToolTipText("");
        btnTrazabilidad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnTrazabilidad.setBorderPainted(false);
        btnTrazabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrazabilidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrazabilidad.setIconTextGap(12);

        btnConsultas.setBackground(new java.awt.Color(0, 51, 51));
        btnConsultas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/consulta.png"))); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.setToolTipText("");
        btnConsultas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnConsultas.setBorderPainted(false);
        btnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultas.setIconTextGap(12);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(0, 51, 51));
        btnProductos.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/productos.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setToolTipText("");
        btnProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProductos.setBorderPainted(false);
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setIconTextGap(12);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNaves, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTransformacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTrazabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrazabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        btnExitX.setFont(new java.awt.Font("Roboto SemiBold", 1, 18)); // NOI18N
        btnExitX.setForeground(new java.awt.Color(0, 51, 51));
        btnExitX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExitX.setText("X");
        btnExitX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        title.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 51, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("GESTIÓN DE PRODUCTOS");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        container.setBackground(new java.awt.Color(255, 255, 255));

        containerTitleBar.setBackground(new java.awt.Color(212, 235, 235));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(0, 51, 51));
        subTitle.setText("Registrar nuevo producto");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(0, 51, 51));
        labelDescripcion.setText("DESCRIPCIÓN");

        jTextDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextDescripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextDescripcion.setBorder(null);
        jTextDescripcion.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextDescripcionMousePressed(evt);
            }
        });
        jTextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        labelPeso.setBackground(new java.awt.Color(255, 255, 255));
        labelPeso.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelPeso.setForeground(new java.awt.Color(0, 51, 51));
        labelPeso.setText("PESO (kg)");

        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));

        jFTextFieldPeso.setBackground(new java.awt.Color(255, 255, 255));
        jFTextFieldPeso.setBorder(null);
        jFTextFieldPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFTextFieldPeso.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFTextFieldPeso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jFTextFieldPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFTextFieldPesoMousePressed(evt);
            }
        });
        jFTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextFieldPesoActionPerformed(evt);
            }
        });

        labelStockMin.setBackground(new java.awt.Color(255, 255, 255));
        labelStockMin.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelStockMin.setForeground(new java.awt.Color(0, 51, 51));
        labelStockMin.setText("STOCK MÍNIMO");

        jFTextFieldStockMin.setBackground(new java.awt.Color(255, 255, 255));
        jFTextFieldStockMin.setBorder(null);
        jFTextFieldStockMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFTextFieldStockMin.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFTextFieldStockMin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jFTextFieldStockMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFTextFieldStockMinMousePressed(evt);
            }
        });
        jFTextFieldStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextFieldStockMinActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 51, 51));

        labelUMedida.setBackground(new java.awt.Color(255, 255, 255));
        labelUMedida.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelUMedida.setForeground(new java.awt.Color(0, 51, 51));
        labelUMedida.setText("UNIDAD DE MEDIDA");

        jComboBoxUMed.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxUMed.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBoxUMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilogramos", "litros", "unidad", "gramos", "mililitros" }));
        jComboBoxUMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelGrupo.setBackground(new java.awt.Color(255, 255, 255));
        labelGrupo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelGrupo.setForeground(new java.awt.Color(0, 51, 51));
        labelGrupo.setText("GRUPO");

        jComboBoxGrupo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxGrupo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "materia prima", "producto final", "producto reenvasado", "" }));
        jComboBoxGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 51));

        btnRegistrarTxt.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        btnRegistrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarTxt.setText("REGISTRAR");
        btnRegistrarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));

        btnLimpiarTxt.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        btnLimpiarTxt.setForeground(new java.awt.Color(0, 51, 51));
        btnLimpiarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarTxt.setText("LIMPIAR");
        btnLimpiarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDescripcion)
                            .addComponent(jSeparator1)
                            .addComponent(labelUMedida)
                            .addComponent(jTextDescripcion)
                            .addComponent(jComboBoxUMed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPeso)
                                    .addComponent(jFTextFieldPeso)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelStockMin)
                                    .addComponent(jFTextFieldStockMin)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelGrupo)
                            .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescripcion)
                            .addComponent(labelPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTextFieldStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(labelStockMin)
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGrupo)
                    .addComponent(labelUMedida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );

        bg.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 580, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarProducto(){
        try {
            String descripcion = jTextDescripcion.getText().trim();
            String unidadMedida = (String) jComboBoxUMed.getSelectedItem();
            double peso = Double.parseDouble(jFTextFieldPeso.getText().replace(",", "."));
            double capacidad = Double.parseDouble(jFTextFieldStockMin.getText().replace(",", "."));

            String respuesta = productoCtrl.agregarProducto(descripcion, unidadMedida, peso, capacidad);

            if (respuesta == null || respuesta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Error al crear el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Producto registrado correctamente:\n" + respuesta, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para peso y capacidad.", "Error de formato", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiarCampos() {
        jTextDescripcion.setText("");
        jFTextFieldPeso.setText("");
        jFTextFieldStockMin.setText("");
        jComboBoxUMed.setSelectedIndex(0);
        jComboBoxGrupo.setSelectedIndex(0);
    }
    
    private void jTextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescripcionActionPerformed

    private void jFTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextFieldPesoActionPerformed

    private void jFTextFieldStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextFieldStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextFieldStockMinActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btnExitXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitXMouseClicked

    private void btnExitXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitXMouseEntered
        btnExit.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnExitXMouseEntered

    private void btnExitXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitXMouseExited
        btnExit.setBackground(Color.WHITE);    
    }//GEN-LAST:event_btnExitXMouseExited

    private void btnRegistrarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTxtMouseEntered
        btnRegistrar.setBackground(new Color(0,87,87)); 
    }//GEN-LAST:event_btnRegistrarTxtMouseEntered

    private void btnRegistrarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTxtMouseExited
        btnRegistrar.setBackground(new Color(0,51,51)); 
    }//GEN-LAST:event_btnRegistrarTxtMouseExited

    private void jTextDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextDescripcionMousePressed

    }//GEN-LAST:event_jTextDescripcionMousePressed

    private void jFTextFieldPesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextFieldPesoMousePressed
     
    }//GEN-LAST:event_jFTextFieldPesoMousePressed

    private void jFTextFieldStockMinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextFieldStockMinMousePressed
        
    }//GEN-LAST:event_jFTextFieldStockMinMousePressed

    private void btnRegistrarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTxtMouseClicked
        registrarProducto();
    }//GEN-LAST:event_btnRegistrarTxtMouseClicked

    private void btnLimpiarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTxtMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarTxtMouseClicked

    private void btnLimpiarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTxtMouseEntered
        btnLimpiar.setBackground(new Color(224,224,224));
    }//GEN-LAST:event_btnLimpiarTxtMouseEntered

    private void btnLimpiarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTxtMouseExited
       btnLimpiar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnLimpiarTxtMouseExited

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnNavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel btnExitX;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JLabel btnLimpiarTxt;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnNaves;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnProductos;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JLabel btnRegistrarTxt;
    private javax.swing.JButton btnTransformacion;
    private javax.swing.JButton btnTrazabilidad;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBoxGrupo;
    private javax.swing.JComboBox<String> jComboBoxUMed;
    private javax.swing.JFormattedTextField jFTextFieldPeso;
    private javax.swing.JFormattedTextField jFTextFieldStockMin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelStockMin;
    private javax.swing.JLabel labelUMedida;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel name;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}

