/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.gui.panels;

import controller.NaveController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ce___
 */
public class ListarNavesYRacks extends javax.swing.JPanel {
    private final DefaultListModel<String> modelo = new DefaultListModel<>();
    private final List<String> naves = NaveController.getInstance().listarNaves();
    
    /**
     * Creates new form Principal
     */
    public ListarNavesYRacks() {
        inicializar();
        mostrarListaNaves();
    }
    
    private void inicializar(){
        initComponents();
        modelo.addElement("");
        racks.setModel(modelo);
        racksTitulo.setVisible(false);
        botonSeleccionar.setVisible(false);
        navesComboBox.setVisible(false);
        noHayNaves.setVisible(false);
    }
    
    private void mostrarListaNaves(){
        if (naves.isEmpty()){
            noHayNaves.setVisible(true);

        } else if (naves.size() > 4){
            navesComboBox.removeAllItems();
            comboBoxNaves();

        } else {
            botonesNave();
        }
    }
    
    private void comboBoxNaves(){
        botonSeleccionar.setVisible(true);
        navesComboBox.setVisible(true);
        
        for (String nave : naves) {
            navesComboBox.addItem(nave);
        }
    }
    
    private void botonesNave(){
        navesPanel.setLayout(new BoxLayout(navesPanel, BoxLayout.X_AXIS));
        navesPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        ImageIcon icono = new ImageIcon("Resources/img/nave.png");
        
        for (String nave : naves) {
            JLabel label = new JLabel(nave, icono, JLabel.LEFT);
            label.setFont(new Font("Roboto", Font.BOLD, 18));
            label.setForeground(Color.WHITE);
            label.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 0));
            label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            
            label.addMouseListener(
                new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        mostrarRacks(nave); 
                    }
                }
            );
            
            navesPanel.add(label);
        }
        
        navesPanel.revalidate();
        navesPanel.repaint();
    }
    
    private void mostrarRacks(String nombreSeleccionado) {
        modelo.clear();
        
        int id = Integer.parseInt(nombreSeleccionado.split(" ")[2]);
        List<String> racksRecibidos = NaveController.getInstance().listarRacks(id);
        
        if (racksRecibidos.isEmpty()){
            modelo.addElement("No hay racks asociados.");

        } else {
            int i = 1;
            
            for (String rack : racksRecibidos){
                int idRack = Integer.parseInt(rack.split(":")[1].split(",")[0].trim());
                String peso = NaveController.getInstance().pesoTotalRack(idRack);
                modelo.addElement(i + ". " + rack + ". Peso actual " + peso);
                System.out.println(rack);
                i++;
            }
        }
        
        racks.setModel(modelo);

        // Hacer visible la lista si estaba oculta
        racksTitulo.setVisible(true);
        racks.revalidate();
        racks.repaint();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        navesPanel = new javax.swing.JPanel();
        navesComboBox = new javax.swing.JComboBox<>();
        botonSeleccionar = new javax.swing.JButton();
        noHayNaves = new javax.swing.JLabel();
        ingrese = new javax.swing.JLabel();
        listaRacks = new javax.swing.JPanel();
        racksTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        racks = new javax.swing.JList<>();

        setBackground(new java.awt.Color(232, 232, 232));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(580, 400));

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Menú naves  >  Listar naves y racks");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navesPanel.setBackground(new java.awt.Color(0, 102, 102));

        navesComboBox.setBackground(new java.awt.Color(255, 255, 255));
        navesComboBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        navesComboBox.setForeground(new java.awt.Color(51, 51, 51));
        navesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        navesComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        botonSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        botonSeleccionar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonSeleccionar.setForeground(new java.awt.Color(0, 51, 51));
        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botonSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        noHayNaves.setBackground(new java.awt.Color(255, 255, 255));
        noHayNaves.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        noHayNaves.setForeground(new java.awt.Color(255, 255, 255));
        noHayNaves.setText("No hay naves registradas");

        javax.swing.GroupLayout navesPanelLayout = new javax.swing.GroupLayout(navesPanel);
        navesPanel.setLayout(navesPanelLayout);
        navesPanelLayout.setHorizontalGroup(
            navesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navesPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(navesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(noHayNaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navesPanelLayout.setVerticalGroup(
            navesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navesPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(navesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noHayNaves))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ingrese.setBackground(new java.awt.Color(255, 255, 255));
        ingrese.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ingrese.setForeground(new java.awt.Color(0, 51, 51));
        ingrese.setText("Seleccione una nave:");

        listaRacks.setBackground(new java.awt.Color(255, 255, 255));

        racksTitulo.setBackground(new java.awt.Color(255, 255, 255));
        racksTitulo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        racksTitulo.setForeground(new java.awt.Color(0, 51, 51));
        racksTitulo.setText("Racks de la nave:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        racks.setBackground(new java.awt.Color(255, 255, 255));
        racks.setBorder(null);
        racks.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        racks.setForeground(new java.awt.Color(102, 102, 102));
        racks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(racks);

        javax.swing.GroupLayout listaRacksLayout = new javax.swing.GroupLayout(listaRacks);
        listaRacks.setLayout(listaRacksLayout);
        listaRacksLayout.setHorizontalGroup(
            listaRacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaRacksLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(listaRacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(racksTitulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listaRacksLayout.setVerticalGroup(
            listaRacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaRacksLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(racksTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listaRacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ingrese)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingrese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaRacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        String nave = (String) navesComboBox.getSelectedItem();
        mostrarRacks(nave);
    }//GEN-LAST:event_botonSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JLabel ingrese;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaRacks;
    private javax.swing.JComboBox<String> navesComboBox;
    private javax.swing.JPanel navesPanel;
    private javax.swing.JLabel noHayNaves;
    private javax.swing.JList<String> racks;
    private javax.swing.JLabel racksTitulo;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
