/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.gui.panels;


import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import view.gui.frames.PrincipalJFrame;

/**
 *
 * @author Ce___
 */
public class Movimientos extends javax.swing.JPanel {
    private PrincipalJFrame frame;
    
    // Panels
    private final OrdenIngreso panelOrdenIngreso;
    private final OrdenEgreso panelOrdenEgreso;
    /**
     * Creates new form Productos
     */
    public Movimientos(PrincipalJFrame frame) {
        this.frame = frame;
        panelOrdenIngreso = new OrdenIngreso(frame);
        panelOrdenEgreso = new OrdenEgreso(frame);
        
        initComponents();
    }
    
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Image backgroundImage = new ImageIcon(getClass().getResource("/img/bgIMG.png")).getImage();
        // Dibujar la imagen de fondo escalada al tamaño del panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        ordenIngreso = new javax.swing.JPanel();
        labelIngreso = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        ordenEgreso = new javax.swing.JPanel();
        labelEgreso = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        ordenInterno = new javax.swing.JPanel();
        arrow4 = new javax.swing.JLabel();
        labelInterno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 232, 232));
        setPreferredSize(new java.awt.Dimension(670, 500));

        container.setBackground(new java.awt.Color(255, 255, 255));

        ordenIngreso.setBackground(new java.awt.Color(212, 235, 235));
        ordenIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordenIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordenIngresoMouseClicked(evt);
            }
        });

        labelIngreso.setBackground(new java.awt.Color(212, 235, 235));
        labelIngreso.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelIngreso.setForeground(new java.awt.Color(0, 51, 51));
        labelIngreso.setText("Generar orden de ingreso");
        labelIngreso.setOpaque(true);

        arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout ordenIngresoLayout = new javax.swing.GroupLayout(ordenIngreso);
        ordenIngreso.setLayout(ordenIngresoLayout);
        ordenIngresoLayout.setHorizontalGroup(
            ordenIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordenIngresoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow)
                .addContainerGap())
        );
        ordenIngresoLayout.setVerticalGroup(
            ordenIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordenIngresoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ordenIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ordenEgreso.setBackground(new java.awt.Color(212, 235, 235));
        ordenEgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordenEgreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordenEgresoMouseClicked(evt);
            }
        });

        labelEgreso.setBackground(new java.awt.Color(212, 235, 235));
        labelEgreso.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelEgreso.setForeground(new java.awt.Color(0, 51, 51));
        labelEgreso.setText("Generar orden de egreso");
        labelEgreso.setOpaque(true);

        arrow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        javax.swing.GroupLayout ordenEgresoLayout = new javax.swing.GroupLayout(ordenEgreso);
        ordenEgreso.setLayout(ordenEgresoLayout);
        ordenEgresoLayout.setHorizontalGroup(
            ordenEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordenEgresoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrow1)
                .addContainerGap())
        );
        ordenEgresoLayout.setVerticalGroup(
            ordenEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordenEgresoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordenEgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ordenInterno.setBackground(new java.awt.Color(212, 235, 235));
        ordenInterno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordenInterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordenInternoMouseClicked(evt);
            }
        });

        arrow4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N

        labelInterno.setBackground(new java.awt.Color(212, 235, 235));
        labelInterno.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelInterno.setForeground(new java.awt.Color(0, 51, 51));
        labelInterno.setText("Generar orden de traslado interno");
        labelInterno.setOpaque(true);

        javax.swing.GroupLayout ordenInternoLayout = new javax.swing.GroupLayout(ordenInterno);
        ordenInterno.setLayout(ordenInternoLayout);
        ordenInternoLayout.setHorizontalGroup(
            ordenInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordenInternoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(labelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(arrow4)
                .addContainerGap())
        );
        ordenInternoLayout.setVerticalGroup(
            ordenInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordenInternoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arrow4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordenInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ordenIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordenEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordenInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ordenIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordenEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordenInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ordenIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordenIngresoMouseClicked
        frame.mostrarJPanel(panelOrdenIngreso);
    }//GEN-LAST:event_ordenIngresoMouseClicked

    private void ordenEgresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordenEgresoMouseClicked
        frame.mostrarJPanel(panelOrdenEgreso);
    }//GEN-LAST:event_ordenEgresoMouseClicked

    private void ordenInternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordenInternoMouseClicked
        
    }//GEN-LAST:event_ordenInternoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow;
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow4;
    private javax.swing.JPanel container;
    private javax.swing.JLabel labelEgreso;
    private javax.swing.JLabel labelIngreso;
    private javax.swing.JLabel labelInterno;
    private javax.swing.JPanel ordenEgreso;
    private javax.swing.JPanel ordenIngreso;
    private javax.swing.JPanel ordenInterno;
    // End of variables declaration//GEN-END:variables
}
