package view.gui.panels;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import view.gui.frames.PrincipalJFrame;

/**
 *
 * @author Ce___
 */
public class OrdenEgreso extends javax.swing.JPanel {
    private PrincipalJFrame frame;
    
    private JPanel botonUbicacionElegido;
    private List<Integer> productos;
    private List<Integer> racksId;
    private List<String> ubicVacias = new ArrayList<String>();
    
    //datos orden    
    private int idRack;
    private String idNave;
    private String ubicacionElegida;
    private int idProducto;
    private int cantidadCargada;
    private LocalDate fecha;
    
    
    /**
     * Creates new form BuscarProducto
     */
    public OrdenEgreso(PrincipalJFrame frame) {
        
        //  MOSTRAR EN LAS UBICACIONES SOLO LAS QUE CONTENGAN STOCK DEL PRODUCTO SELECCIONADO!!!!!!
        
        initComponents();
        panelSinProductos3.setVisible(false);
        this.frame = frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        container = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        panelSinProductos3 = new javax.swing.JPanel();
        ingrese8 = new javax.swing.JLabel();
        volver3 = new javax.swing.JButton();

        popup.setFocusable(false);

        setBackground(new java.awt.Color(232, 232, 232));
        setPreferredSize(new java.awt.Dimension(670, 500));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(580, 400));

        fondo.setMaximumSize(new java.awt.Dimension(580, 326));
        fondo.setMinimumSize(new java.awt.Dimension(580, 326));
        fondo.setPreferredSize(new java.awt.Dimension(580, 326));
        fondo.setLayout(new java.awt.BorderLayout());

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Menú movimientos  >  Generar orden de egreso");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSinProductos3.setBackground(new java.awt.Color(255, 255, 255));

        ingrese8.setBackground(new java.awt.Color(255, 255, 255));
        ingrese8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ingrese8.setForeground(new java.awt.Color(0, 51, 51));
        ingrese8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingrese8.setText("<html>No hay productos cargados para generar una orden de ingreso<html>");
        ingrese8.setToolTipText("");

        volver3.setBackground(new java.awt.Color(0, 51, 51));
        volver3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        volver3.setForeground(new java.awt.Color(255, 255, 255));
        volver3.setText("Volver al menú movimientos");
        volver3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        volver3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSinProductos3Layout = new javax.swing.GroupLayout(panelSinProductos3);
        panelSinProductos3.setLayout(panelSinProductos3Layout);
        panelSinProductos3Layout.setHorizontalGroup(
            panelSinProductos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinProductos3Layout.createSequentialGroup()
                .addGroup(panelSinProductos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSinProductos3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(volver3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSinProductos3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(ingrese8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        panelSinProductos3Layout.setVerticalGroup(
            panelSinProductos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinProductos3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(ingrese8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(volver3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSinProductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                    .addGap(0, 53, Short.MAX_VALUE)
                    .addComponent(panelSinProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                    .addGap(0, 54, Short.MAX_VALUE)
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        frame.mostrarJPanel(frame.getPanelMovimientos());
    }//GEN-LAST:event_volverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel ingrese8;
    private javax.swing.JPanel panelSinProductos3;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JLabel subTitle;
    private javax.swing.JButton volver3;
    // End of variables declaration//GEN-END:variables
}
