/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.gui.panels;

import controller.NaveController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.util.Collections;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Ce___
 */
public class PesoUbicacionesRack extends javax.swing.JPanel {
    private final List<Integer> racksId = NaveController.getInstance().listarTodosLosRacks();
    private int idRack;
    
    /**
     * Creates new form PesoUbicacionesRack
     */
    public PesoUbicacionesRack() {
        inicializar();
    }
    
    private void inicializar(){
        initComponents();
        
        racksComboBox.removeAllItems();
        for (int id : racksId){
            racksComboBox.addItem("ID " + id);
        }
        
        aplicarNombres();
        visibilidadUbicaciones(false);
    }
      
    private void aplicarNombres(){
        pesoF1C1.setName("pesoF1C1");
        pesoF1C2.setName("pesoF1C2");
        pesoF1C3.setName("pesoF1C3");

        pesoF2C1.setName("pesoF2C1");
        pesoF2C2.setName("pesoF2C2");
        pesoF2C3.setName("pesoF2C3");

        pesoF3C1.setName("pesoF3C1");
        pesoF3C2.setName("pesoF3C2");
        pesoF3C3.setName("pesoF3C3");
    }
    
    private void pintarPesos(){
        List<String> pesosResp = NaveController.getInstance().calcularPesosRack(idRack);
        
        Collections.sort(pesosResp);
        String[] pesos = pesosResp.toArray(String[]::new);
        
        int index = 0;
        
        for (int i = 1; i < 4; i++){
            for (int j = 1; j < 4; j++){
                String nombre = "pesoF" + i + "C" + j;
                String peso = pesos[index].split(" ")[1];
                String codigoUbicacion = pesos[index].split(" ")[0].split(":")[0];

                JLabel label = buscarLabelPorNombreEnPanel(this, nombre);
                
                if (label != null) {
                    boolean llena = NaveController.getInstance().ubicacionLlena(codigoUbicacion);
                    Component padre = label.getParent();
                    
                    if (!llena){
                        label.setText(peso);
                        padre.setBackground(new Color(232,232,232));
                    } else {
                        padre.setBackground(new Color(229,155,129));
                        label.setText("LLENO");
                    }
                    
                    index++;
                } else {
                    System.out.println("No existe ese JLabel.");
                }
            }
        }
    }
    
    public JLabel buscarLabelPorNombreEnPanel(Container container, String nombreBuscado) {
        for (Component comp : container.getComponents()) {

            if (comp instanceof JLabel && nombreBuscado.equals(comp.getName())) {
                return (JLabel) comp;
            }

            if (comp instanceof Container) {
                JLabel resultado = buscarLabelPorNombreEnPanel((Container) comp, nombreBuscado);
                if (resultado != null) return resultado;
            }
        }
        
        return null;
    }
    
    private void visibilidadUbicaciones(boolean visible){
        rack.setVisible(visible);
        
        f1c1.setVisible(visible);
        pesoF1C1.setVisible(visible);
        codigo1.setVisible(visible);
        
        f1c2.setVisible(visible);
        pesoF1C2.setVisible(visible);
        codigo.setVisible(visible);
        
        f1c3.setVisible(visible);
        pesoF1C3.setVisible(visible);
        codigo4.setVisible(visible);
        
        f2c1.setVisible(visible);
        pesoF2C1.setVisible(visible);
        codigo5.setVisible(visible);
        
        f2c2.setVisible(visible);
        pesoF2C2.setVisible(visible);
        codigo6.setVisible(visible);
        
        f2c3.setVisible(visible);
        pesoF2C3.setVisible(visible);
        codigo7.setVisible(visible);
        
        f3c1.setVisible(visible);
        pesoF3C1.setVisible(visible);
        codigo9.setVisible(visible);
        
        f3c2.setVisible(visible);
        pesoF3C2.setVisible(visible);
        codigo10.setVisible(visible);
        
        f3c3.setVisible(visible);
        pesoF3C3.setVisible(visible);
        codigo12.setVisible(visible);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        ingrese = new javax.swing.JLabel();
        racksComboBox = new javax.swing.JComboBox<>();
        botonSeleccionar = new javax.swing.JButton();
        rack = new javax.swing.JLabel();
        f1c1 = new javax.swing.JPanel();
        codigo1 = new javax.swing.JLabel();
        pesoF1C1 = new javax.swing.JLabel();
        f1c2 = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        pesoF1C2 = new javax.swing.JLabel();
        f1c3 = new javax.swing.JPanel();
        codigo4 = new javax.swing.JLabel();
        pesoF1C3 = new javax.swing.JLabel();
        f2c1 = new javax.swing.JPanel();
        codigo5 = new javax.swing.JLabel();
        pesoF2C1 = new javax.swing.JLabel();
        f2c2 = new javax.swing.JPanel();
        codigo6 = new javax.swing.JLabel();
        pesoF2C2 = new javax.swing.JLabel();
        f2c3 = new javax.swing.JPanel();
        codigo7 = new javax.swing.JLabel();
        pesoF2C3 = new javax.swing.JLabel();
        f3c1 = new javax.swing.JPanel();
        codigo9 = new javax.swing.JLabel();
        pesoF3C1 = new javax.swing.JLabel();
        f3c2 = new javax.swing.JPanel();
        codigo10 = new javax.swing.JLabel();
        pesoF3C2 = new javax.swing.JLabel();
        f3c3 = new javax.swing.JPanel();
        codigo12 = new javax.swing.JLabel();
        pesoF3C3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(580, 400));

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Menú naves  >  Peso de ubicaciones disponibles");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        ingrese.setBackground(new java.awt.Color(255, 255, 255));
        ingrese.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ingrese.setForeground(new java.awt.Color(0, 51, 51));
        ingrese.setText("Seleccione un rack:");

        racksComboBox.setBackground(new java.awt.Color(255, 255, 255));
        racksComboBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        racksComboBox.setForeground(new java.awt.Color(51, 51, 51));
        racksComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        racksComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 227, 227)));
        racksComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racksComboBoxActionPerformed(evt);
            }
        });

        botonSeleccionar.setBackground(new java.awt.Color(0, 51, 51));
        botonSeleccionar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        botonSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        rack.setBackground(new java.awt.Color(0, 51, 51));
        rack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        rack.setForeground(new java.awt.Color(0, 51, 51));
        rack.setText("RACK ID X");

        f1c1.setBackground(new java.awt.Color(232, 232, 232));

        codigo1.setBackground(new java.awt.Color(0, 51, 51));
        codigo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo1.setForeground(new java.awt.Color(0, 51, 51));
        codigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo1.setText("Fila 1 Columna 1");

        pesoF1C1.setBackground(new java.awt.Color(0, 51, 51));
        pesoF1C1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF1C1.setForeground(new java.awt.Color(0, 51, 51));
        pesoF1C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF1C1.setText("X kg");

        javax.swing.GroupLayout f1c1Layout = new javax.swing.GroupLayout(f1c1);
        f1c1.setLayout(f1c1Layout);
        f1c1Layout.setHorizontalGroup(
            f1c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1c1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesoF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(codigo1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        f1c1Layout.setVerticalGroup(
            f1c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1c1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF1C1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        f1c2.setBackground(new java.awt.Color(232, 232, 232));

        codigo.setBackground(new java.awt.Color(0, 51, 51));
        codigo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo.setForeground(new java.awt.Color(0, 51, 51));
        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo.setText("Fila 1 Columna 2");

        pesoF1C2.setBackground(new java.awt.Color(0, 51, 51));
        pesoF1C2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF1C2.setForeground(new java.awt.Color(0, 51, 51));
        pesoF1C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF1C2.setText("X kg");

        javax.swing.GroupLayout f1c2Layout = new javax.swing.GroupLayout(f1c2);
        f1c2.setLayout(f1c2Layout);
        f1c2Layout.setHorizontalGroup(
            f1c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1c2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f1c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesoF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f1c2Layout.setVerticalGroup(
            f1c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1c2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF1C2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        f1c3.setBackground(new java.awt.Color(232, 232, 232));

        codigo4.setBackground(new java.awt.Color(0, 51, 51));
        codigo4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo4.setForeground(new java.awt.Color(0, 51, 51));
        codigo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo4.setText("Fila 1 Columna 3");

        pesoF1C3.setBackground(new java.awt.Color(0, 51, 51));
        pesoF1C3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF1C3.setForeground(new java.awt.Color(0, 51, 51));
        pesoF1C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF1C3.setText("X kg");

        javax.swing.GroupLayout f1c3Layout = new javax.swing.GroupLayout(f1c3);
        f1c3.setLayout(f1c3Layout);
        f1c3Layout.setHorizontalGroup(
            f1c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1c3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f1c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesoF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(codigo4, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f1c3Layout.setVerticalGroup(
            f1c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1c3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF1C3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        f2c1.setBackground(new java.awt.Color(232, 232, 232));

        codigo5.setBackground(new java.awt.Color(0, 51, 51));
        codigo5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo5.setForeground(new java.awt.Color(0, 51, 51));
        codigo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo5.setText("Fila 2 Columna 1");

        pesoF2C1.setBackground(new java.awt.Color(0, 51, 51));
        pesoF2C1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF2C1.setForeground(new java.awt.Color(0, 51, 51));
        pesoF2C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF2C1.setText("X kg");

        javax.swing.GroupLayout f2c1Layout = new javax.swing.GroupLayout(f2c1);
        f2c1.setLayout(f2c1Layout);
        f2c1Layout.setHorizontalGroup(
            f2c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2c1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f2c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(pesoF2C1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f2c1Layout.setVerticalGroup(
            f2c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2c1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF2C1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        f2c2.setBackground(new java.awt.Color(232, 232, 232));

        codigo6.setBackground(new java.awt.Color(0, 51, 51));
        codigo6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo6.setForeground(new java.awt.Color(0, 51, 51));
        codigo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo6.setText("Fila 2 Columna 2");

        pesoF2C2.setBackground(new java.awt.Color(0, 51, 51));
        pesoF2C2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF2C2.setForeground(new java.awt.Color(0, 51, 51));
        pesoF2C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF2C2.setText("X kg");

        javax.swing.GroupLayout f2c2Layout = new javax.swing.GroupLayout(f2c2);
        f2c2.setLayout(f2c2Layout);
        f2c2Layout.setHorizontalGroup(
            f2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2c2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo6, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(pesoF2C2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f2c2Layout.setVerticalGroup(
            f2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2c2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF2C2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        f2c3.setBackground(new java.awt.Color(232, 232, 232));

        codigo7.setBackground(new java.awt.Color(0, 51, 51));
        codigo7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo7.setForeground(new java.awt.Color(0, 51, 51));
        codigo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo7.setText("Fila 2 Columna 3");

        pesoF2C3.setBackground(new java.awt.Color(0, 51, 51));
        pesoF2C3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF2C3.setForeground(new java.awt.Color(0, 51, 51));
        pesoF2C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF2C3.setText("X kg");

        javax.swing.GroupLayout f2c3Layout = new javax.swing.GroupLayout(f2c3);
        f2c3.setLayout(f2c3Layout);
        f2c3Layout.setHorizontalGroup(
            f2c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2c3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f2c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo7, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(pesoF2C3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f2c3Layout.setVerticalGroup(
            f2c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2c3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF2C3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        f3c1.setBackground(new java.awt.Color(232, 232, 232));

        codigo9.setBackground(new java.awt.Color(0, 51, 51));
        codigo9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo9.setForeground(new java.awt.Color(0, 51, 51));
        codigo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo9.setText("Fila 3 Columna 1");

        pesoF3C1.setBackground(new java.awt.Color(0, 51, 51));
        pesoF3C1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF3C1.setForeground(new java.awt.Color(0, 51, 51));
        pesoF3C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF3C1.setText("X kg");

        javax.swing.GroupLayout f3c1Layout = new javax.swing.GroupLayout(f3c1);
        f3c1.setLayout(f3c1Layout);
        f3c1Layout.setHorizontalGroup(
            f3c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3c1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f3c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo9, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(pesoF3C1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f3c1Layout.setVerticalGroup(
            f3c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3c1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF3C1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        f3c2.setBackground(new java.awt.Color(232, 232, 232));

        codigo10.setBackground(new java.awt.Color(0, 51, 51));
        codigo10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo10.setForeground(new java.awt.Color(0, 51, 51));
        codigo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo10.setText("Fila 3 Columna 2");

        pesoF3C2.setBackground(new java.awt.Color(0, 51, 51));
        pesoF3C2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF3C2.setForeground(new java.awt.Color(0, 51, 51));
        pesoF3C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF3C2.setText("X kg");

        javax.swing.GroupLayout f3c2Layout = new javax.swing.GroupLayout(f3c2);
        f3c2.setLayout(f3c2Layout);
        f3c2Layout.setHorizontalGroup(
            f3c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3c2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f3c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo10, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(pesoF3C2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f3c2Layout.setVerticalGroup(
            f3c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3c2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF3C2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        f3c3.setBackground(new java.awt.Color(232, 232, 232));

        codigo12.setBackground(new java.awt.Color(0, 51, 51));
        codigo12.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo12.setForeground(new java.awt.Color(0, 51, 51));
        codigo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo12.setText("Fila 3 Columna 3");

        pesoF3C3.setBackground(new java.awt.Color(0, 51, 51));
        pesoF3C3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        pesoF3C3.setForeground(new java.awt.Color(0, 51, 51));
        pesoF3C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoF3C3.setText("X kg");

        javax.swing.GroupLayout f3c3Layout = new javax.swing.GroupLayout(f3c3);
        f3c3.setLayout(f3c3Layout);
        f3c3Layout.setHorizontalGroup(
            f3c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3c3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f3c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo12, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(pesoF3C3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        f3c3Layout.setVerticalGroup(
            f3c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3c3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoF3C3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(f2c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f3c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(f1c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(f1c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(f2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(f2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(f3c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(f3c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(rack))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ingrese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(racksComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingrese)
                    .addComponent(racksComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f1c3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f1c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(f2c2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f2c1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(f3c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(f3c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(f3c3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void racksComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racksComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_racksComboBoxActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        String rackSeleccionado = (String) racksComboBox.getSelectedItem();
        idRack = Integer.parseInt(rackSeleccionado.split(" ")[1]);
        
        rack.setText("RACK " + rackSeleccionado);
        pintarPesos();
        visibilidadUbicaciones(true);
    }//GEN-LAST:event_botonSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo1;
    private javax.swing.JLabel codigo10;
    private javax.swing.JLabel codigo12;
    private javax.swing.JLabel codigo4;
    private javax.swing.JLabel codigo5;
    private javax.swing.JLabel codigo6;
    private javax.swing.JLabel codigo7;
    private javax.swing.JLabel codigo9;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JPanel f1c1;
    private javax.swing.JPanel f1c2;
    private javax.swing.JPanel f1c3;
    private javax.swing.JPanel f2c1;
    private javax.swing.JPanel f2c2;
    private javax.swing.JPanel f2c3;
    private javax.swing.JPanel f3c1;
    private javax.swing.JPanel f3c2;
    private javax.swing.JPanel f3c3;
    private javax.swing.JLabel ingrese;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pesoF1C1;
    private javax.swing.JLabel pesoF1C2;
    private javax.swing.JLabel pesoF1C3;
    private javax.swing.JLabel pesoF2C1;
    private javax.swing.JLabel pesoF2C2;
    private javax.swing.JLabel pesoF2C3;
    private javax.swing.JLabel pesoF3C1;
    private javax.swing.JLabel pesoF3C2;
    private javax.swing.JLabel pesoF3C3;
    private javax.swing.JLabel rack;
    private javax.swing.JComboBox<String> racksComboBox;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
