/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.gui.panels;

import java.awt.Color;

/**
 *
 * @author Ce___
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        containerTitleBar = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        labelNaves = new javax.swing.JLabel();
        cantNaves = new javax.swing.JLabel();
        labelRacks = new javax.swing.JLabel();
        cantRacks = new javax.swing.JLabel();
        cantMovimientos = new javax.swing.JLabel();
        labelMovimientos = new javax.swing.JLabel();
        labelProductos = new javax.swing.JLabel();
        cantProductos = new javax.swing.JLabel();
        inventarioBackground = new javax.swing.JPanel();
        labelBajoStock = new javax.swing.JLabel();
        cantBajoStock = new javax.swing.JLabel();
        cantSinStock = new javax.swing.JLabel();
        labelSinStock = new javax.swing.JLabel();
        btnVerAlertaStock = new javax.swing.JPanel();
        btnVerAlertaStockTxt = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(232, 232, 232));

        container.setBackground(new java.awt.Color(255, 255, 255));

        containerTitleBar.setBackground(new java.awt.Color(0, 51, 51));

        subTitle.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Bienvenido/a");

        javax.swing.GroupLayout containerTitleBarLayout = new javax.swing.GroupLayout(containerTitleBar);
        containerTitleBar.setLayout(containerTitleBarLayout);
        containerTitleBarLayout.setHorizontalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerTitleBarLayout.setVerticalGroup(
            containerTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelNaves.setBackground(new java.awt.Color(255, 255, 255));
        labelNaves.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNaves.setForeground(new java.awt.Color(0, 51, 51));
        labelNaves.setText("Naves");

        cantNaves.setBackground(new java.awt.Color(255, 255, 255));
        cantNaves.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cantNaves.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cantNaves.setText("{n}");

        labelRacks.setBackground(new java.awt.Color(255, 255, 255));
        labelRacks.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelRacks.setForeground(new java.awt.Color(0, 51, 51));
        labelRacks.setText("Racks");

        cantRacks.setBackground(new java.awt.Color(255, 255, 255));
        cantRacks.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cantRacks.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cantRacks.setText("{n}");

        cantMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        cantMovimientos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cantMovimientos.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cantMovimientos.setText("{n}");

        labelMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        labelMovimientos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelMovimientos.setForeground(new java.awt.Color(0, 51, 51));
        labelMovimientos.setText("Movimientos realizados");

        labelProductos.setBackground(new java.awt.Color(255, 255, 255));
        labelProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelProductos.setForeground(new java.awt.Color(0, 51, 51));
        labelProductos.setText("Productos registrados");

        cantProductos.setBackground(new java.awt.Color(255, 255, 255));
        cantProductos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cantProductos.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cantProductos.setText("{n}");

        inventarioBackground.setBackground(new java.awt.Color(212, 235, 235));

        labelBajoStock.setBackground(new java.awt.Color(255, 255, 255));
        labelBajoStock.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelBajoStock.setForeground(new java.awt.Color(0, 51, 51));
        labelBajoStock.setText("BAJO STOCK");

        cantBajoStock.setBackground(new java.awt.Color(255, 255, 255));
        cantBajoStock.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        cantBajoStock.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cantBajoStock.setText("{n}");

        cantSinStock.setBackground(new java.awt.Color(255, 255, 255));
        cantSinStock.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        cantSinStock.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cantSinStock.setText("{n} ");

        labelSinStock.setBackground(new java.awt.Color(255, 255, 255));
        labelSinStock.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelSinStock.setForeground(new java.awt.Color(0, 51, 51));
        labelSinStock.setText("SIN STOCK");

        btnVerAlertaStock.setBackground(new java.awt.Color(255, 204, 0));

        btnVerAlertaStockTxt.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        btnVerAlertaStockTxt.setForeground(new java.awt.Color(0, 0, 0));
        btnVerAlertaStockTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerAlertaStockTxt.setText("Ver alertas de stock");
        btnVerAlertaStockTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerAlertaStockTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerAlertaStockTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerAlertaStockTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerAlertaStockTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVerAlertaStockLayout = new javax.swing.GroupLayout(btnVerAlertaStock);
        btnVerAlertaStock.setLayout(btnVerAlertaStockLayout);
        btnVerAlertaStockLayout.setHorizontalGroup(
            btnVerAlertaStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerAlertaStockLayout.createSequentialGroup()
                .addComponent(btnVerAlertaStockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnVerAlertaStockLayout.setVerticalGroup(
            btnVerAlertaStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerAlertaStockLayout.createSequentialGroup()
                .addComponent(btnVerAlertaStockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inventarioBackgroundLayout = new javax.swing.GroupLayout(inventarioBackground);
        inventarioBackground.setLayout(inventarioBackgroundLayout);
        inventarioBackgroundLayout.setHorizontalGroup(
            inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioBackgroundLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventarioBackgroundLayout.createSequentialGroup()
                        .addComponent(btnVerAlertaStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inventarioBackgroundLayout.createSequentialGroup()
                        .addGroup(inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantBajoStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelBajoStock, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantSinStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSinStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        inventarioBackgroundLayout.setVerticalGroup(
            inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cantBajoStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantSinStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inventarioBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSinStock)
                    .addComponent(labelBajoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnVerAlertaStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cantMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelNaves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantNaves, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cantRacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cantProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addComponent(inventarioBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(containerTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNaves)
                    .addComponent(labelRacks))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMovimientos)
                    .addComponent(labelProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(inventarioBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addGap(0, 45, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 45, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerAlertaStockTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerAlertaStockTxtMouseClicked
        //TODO
    }//GEN-LAST:event_btnVerAlertaStockTxtMouseClicked

    private void btnVerAlertaStockTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerAlertaStockTxtMouseEntered
        btnVerAlertaStock.setBackground(new Color(255,220,84));
    }//GEN-LAST:event_btnVerAlertaStockTxtMouseEntered

    private void btnVerAlertaStockTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerAlertaStockTxtMouseExited
        btnVerAlertaStock.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnVerAlertaStockTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnVerAlertaStock;
    private javax.swing.JLabel btnVerAlertaStockTxt;
    private javax.swing.JLabel cantBajoStock;
    private javax.swing.JLabel cantMovimientos;
    private javax.swing.JLabel cantNaves;
    private javax.swing.JLabel cantProductos;
    private javax.swing.JLabel cantRacks;
    private javax.swing.JLabel cantSinStock;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerTitleBar;
    private javax.swing.JPanel inventarioBackground;
    private javax.swing.JLabel labelBajoStock;
    private javax.swing.JLabel labelMovimientos;
    private javax.swing.JLabel labelNaves;
    private javax.swing.JLabel labelProductos;
    private javax.swing.JLabel labelRacks;
    private javax.swing.JLabel labelSinStock;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
