/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui.frames;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

import view.gui.panels.Principal;
import view.gui.panels.Movimientos;
import view.gui.panels.Naves;
import view.gui.panels.Productos;

/**
 *
 * @author Ce___
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private JPanel placeholder;
    private JButton botonActual;

    private Principal panelPrincipal;
    private Naves panelNaves;
    private Movimientos panelMovimientos;
    private Productos panelProductos;

    /**
     * Creates new form NuevoProductoJFrame
     */
    public PrincipalJFrame() {
        inicializarPanels();
        initComponents();
        crearPlaceHolder();
    }
    
    private void crearPlaceHolder(){
        placeholder = new JPanel(new BorderLayout());
        placeholder.setBounds(230, 100, 670, 500);
        bg.add(placeholder, BorderLayout.CENTER);
        btnPrincipal.setBackground(new Color(0,75,75));
        botonActual = btnPrincipal;
                
        mostrarJPanel(panelPrincipal);
    }
    
    public void mostrarJPanel(JPanel p){
        p.setSize(670,500);
        p.setLocation(0,0);
        
        placeholder.removeAll();
        placeholder.add(p, BorderLayout.CENTER);
        placeholder.revalidate();
        placeholder.repaint();
    }
    
    private void inicializarPanels(){
        panelPrincipal = new Principal();
        panelMovimientos = new Movimientos(this);
        panelNaves = new Naves(this);
        panelProductos = new Productos(this);
    }

    private void seleccionBoton(JButton nuevoBoton){
        botonActual.setBackground(new Color(0,51,51));
        botonActual = nuevoBoton;
        botonActual.setBackground(new Color(0,75,75));
    }
    
    // GETTERS
    
    public Principal getPanelPrincipal() {
        return panelPrincipal;
    }

    public Movimientos getPanelMovimientos() {
        return panelMovimientos;
    }

    public Naves getPanelNaves() {
        return panelNaves;
    }

    public Productos getPanelProductos() {
        return panelProductos;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        btnPrincipal = new javax.swing.JButton();
        btnNaves = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnMovimientos = new javax.swing.JButton();
        btnTransformacion = new javax.swing.JButton();
        btnTrazabilidad = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        btnExitX = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(232, 232, 232));
        bg.setMinimumSize(new java.awt.Dimension(900, 600));
        bg.setPreferredSize(new java.awt.Dimension(900, 600));

        menu.setBackground(new java.awt.Color(0, 51, 51));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("WMS");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(512, 512));
        logo.setMinimumSize(new java.awt.Dimension(512, 512));
        logo.setPreferredSize(new java.awt.Dimension(512, 512));

        btnPrincipal.setBackground(new java.awt.Color(0, 75, 75));
        btnPrincipal.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.setToolTipText("");
        btnPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal.setBorderPainted(false);
        btnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal.setIconTextGap(12);
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        btnNaves.setBackground(new java.awt.Color(0, 51, 51));
        btnNaves.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnNaves.setForeground(new java.awt.Color(255, 255, 255));
        btnNaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nave.png"))); // NOI18N
        btnNaves.setText("Naves");
        btnNaves.setToolTipText("");
        btnNaves.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnNaves.setBorderPainted(false);
        btnNaves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNaves.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNaves.setIconTextGap(12);
        btnNaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNavesMouseClicked(evt);
            }
        });
        btnNaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavesActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(0, 51, 51));
        btnProductos.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productos.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setToolTipText("");
        btnProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProductos.setBorderPainted(false);
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setIconTextGap(12);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnMovimientos.setBackground(new java.awt.Color(0, 51, 51));
        btnMovimientos.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/movimientos.png"))); // NOI18N
        btnMovimientos.setText("Movimientos");
        btnMovimientos.setToolTipText("");
        btnMovimientos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMovimientos.setBorderPainted(false);
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMovimientos.setIconTextGap(12);
        btnMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovimientosMouseClicked(evt);
            }
        });
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });

        btnTransformacion.setBackground(new java.awt.Color(0, 51, 51));
        btnTransformacion.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnTransformacion.setForeground(new java.awt.Color(255, 255, 255));
        btnTransformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transformacion.png"))); // NOI18N
        btnTransformacion.setText("Transformación");
        btnTransformacion.setToolTipText("");
        btnTransformacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnTransformacion.setBorderPainted(false);
        btnTransformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransformacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransformacion.setIconTextGap(12);

        btnTrazabilidad.setBackground(new java.awt.Color(0, 51, 51));
        btnTrazabilidad.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnTrazabilidad.setForeground(new java.awt.Color(255, 255, 255));
        btnTrazabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial.png"))); // NOI18N
        btnTrazabilidad.setText("Trazabilidad");
        btnTrazabilidad.setToolTipText("");
        btnTrazabilidad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnTrazabilidad.setBorderPainted(false);
        btnTrazabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrazabilidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrazabilidad.setIconTextGap(12);

        btnConsultas.setBackground(new java.awt.Color(0, 51, 51));
        btnConsultas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consulta.png"))); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.setToolTipText("");
        btnConsultas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(0, 0, 0)));
        btnConsultas.setBorderPainted(false);
        btnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultas.setIconTextGap(12);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTransformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTrazabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnTransformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnTrazabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        btnExitX.setFont(new java.awt.Font("Roboto SemiBold", 1, 18)); // NOI18N
        btnExitX.setForeground(new java.awt.Color(0, 51, 51));
        btnExitX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExitX.setText("X");
        btnExitX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        title.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 51, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("MENÚ PRINCIPAL");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btnExitXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitXMouseExited
        btnExit.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnExitXMouseExited

    private void btnExitXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitXMouseEntered
        btnExit.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnExitXMouseEntered

    private void btnExitXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitXMouseClicked

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        mostrarJPanel(panelProductos);
        seleccionBoton(btnProductos);
        title.setText("MENÚ PRODUCTOS");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        //menuMovimientosPanel = new Movimientos(this, movimientoCtrl, productoCtrl, naveCtrl);
        mostrarJPanel(panelMovimientos);
        title.setText("MENÚ ORDENES DE MOVIMIENTO");
        seleccionBoton(btnMovimientos);
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void btnNavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavesActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        mostrarJPanel(panelPrincipal);
        title.setText("MENÚ PRINCIPAL");
        seleccionBoton(btnPrincipal);
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnNavesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNavesMouseClicked
        mostrarJPanel(panelNaves);
        title.setText("MENÚ NAVES");
        seleccionBoton(btnNaves);
    }//GEN-LAST:event_btnNavesMouseClicked

    private void btnMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovimientosMouseClicked

    }//GEN-LAST:event_btnMovimientosMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel btnExitX;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnNaves;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnTransformacion;
    private javax.swing.JButton btnTrazabilidad;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel name;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}

